version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - "obalunenko"
    reviewers:
      - "obalunenko"
    commit-message:
      prefix: "chore"
      include: "scope"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    assignees:
      - "obalunenko"
    reviewers:
      - "obalunenko"
    commit-message:
      prefix: "chore"
      include: "scope"

  
  - package-ecosystem: "docker"
    directory: "/build/docker/"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    assignees:
      - "obalunenko"
    reviewers:
      - "obalunenko"
    commit-message:
      prefix: "chore"
      include: "scope"


