// Code generated by "stringer -type=reportType"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[reportTypeUnknown-0]
	_ = x[reportType1-1]
	_ = x[reportType2-2]
	_ = x[reportTypeSentinel-3]
}

const _reportType_name = "reportTypeUnknownreportType1reportType2reportTypeSentinel"

var _reportType_index = [...]uint8{0, 17, 28, 39, 57}

func (i reportType) String() string {
	if i < 0 || i >= reportType(len(_reportType_index)-1) {
		return "reportType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _reportType_name[_reportType_index[i]:_reportType_index[i+1]]
}
