release:
  github:
    owner: oleg-balunenko
    name: spamassassin-parser

env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - GOPROXY=https://gocenter.io
before:
  hooks:
    - go mod tidy

builds:
  - id: service
    binary: spamassassin-parser
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
      - 386
      - arm
    main: ./cmd/spamassassin-parser
    ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}} -X main.date={{.Date}}

dockers:
  - dockerfile: Dockerfile
    binaries:
      - spamassassin-parser
    image_templates:
      - "olegbalunenko/spamassassin-parser:latest"
      - "olegbalunenko/spamassassin-parser:{{ .Tag }}"
      - "olegbalunenko/spamassassin-parser:v{{ .Major }}.{{ .Minor }}"

archives:
  - id: service
    builds:
      - service
    format: tar.gz
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      amd64: 64-bit
      386: 32-bit
      darwin: macOS
      linux: Tux
    name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^dev:"
      - "README"
      - "^readme"
      - "^scripts"
      - "scripts:"
      - Merge pull request
      - Merge branch
      - Rebase on master
      - "^Makefile"
      - "goreleaser"
