name: Build and push base docker images [lint]

on:
  push:
    branches:
      - "master"
    paths:
      - "!**"
      - "build/docker/base/**"
      - ".github/workflows/docker-build-push-base.yml"

env:
  DOCKER_REPO: ghcr.io/obalunenko/


jobs:
  build-base:
    name: "Build base images"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PACKAGES_RW }}
  
      - name: Run build base images
        run: |
          make docker-build-base

      - name: Push images to registry
        run: |
          make docker-push-prod-images
